services:
  hoodly-web:
    image: ghcr.io/lennyblk/hoodly-web:latest
    container_name: hoodly-web
    restart: unless-stopped
    networks:
      - proxy

  hoodly-api:
    image: ghcr.io/lennyblk/hoodly-api:latest
    container_name: hoodly-api
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/data
    depends_on:
      - hoodly-mongo
      - hoodly-neo4j
    networks:
      - proxy
      - internal

  hoodly-mongo:
    image: mongo:7
    container_name: hoodly-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: hoodly
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - internal

  hoodly-neo4j:
    image: neo4j:5
    container_name: hoodly-neo4j
    restart: unless-stopped
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    networks:
      - internal

volumes:
  mongo_data:
  neo4j_data:
  sqlite_data:

networks:
  proxy:
    external: true
    name: proxy
  internal:
    internal: true
