services:
  stremio:
    image: tsaridas/stremio-docker:latest
    container_name: stremio
    restart: unless-stopped
    environment:
      - NO_CORS=1
      - SERVER_URL=https://stremio.lennyblk.dev/
    volumes:
      - stremio_data:/root/.stremio-server
    networks:
      - proxy

volumes:
  stremio_data:
    name: stremio_data

networks:
  proxy:
    external: true
    name: proxy
