services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - TZ=Europe/Paris
      - JELLYFIN_PublishedServerUrl=https://jellyfin.lennyblk.dev
    volumes:
      - /opt/jellyfin/config:/config
      - /opt/jellyfin/cache:/cache
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
