services:
  dashdot:
    image: mauricenino/dashdot:latest
    container_name: dashdot
    privileged: true
    environment:
      - TZ=Europe/Paris
      - DASHDOT_OVERRIDE_OS=Ubuntu
      - DASHDOT_CUSTOM_GRAPHS=storage
      - DASHDOT_STORAGE_POLL_INTERVAL=60000
    volumes:
      - /:/mnt/host:ro
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
